### PR TITLE
Fixed Checkbox disabled+checked crash

### PR DESCRIPTION
**Pull request by DDobrowolski**

### CODE REVIEW

**Comment by aaronisrael** [comment]
What is the reason to have a fixed color, this will likely break the checkbox in other themes.

**Comment by DDobrowolski** [comment]
> What is the reason to have a fixed color, this will likely break the checkbox in other themes.

image
It gives an error when Checkbox is `disabled` and `checked` in same time

**Comment by aaronisrael** [comment]
Do you have a theme provider?

**Comment by DDobrowolski** [comment]
Yes

**Comment by aaronisrael** [comment]
colors should be accessed in styled-components and not as a prop.
`color: ${({ theme }) => theme.ui.disabled};`

**Pull request merged**
